---


- name: create_empty_file
  copy:
    content: ""
    dest: /etc/iaac
    force: no
    group: sys
    owner: root
    mode: 0500
    
    
- name: version 
  set_fact:
      ver: "{{ ansible_distribution }} / {{ ansible_distribution_version}}"
      

