---        

- hosts: iaas
  user: root
  tasks:
    - include: /home/ars/ops/roles/tasks/create_file/main.yml
      tags: create_empty_file
      name: create_empty_file
   
- hosts: all
  user: root
  tasks:
    - include: /home/ars/ops/roles/tasks/name_distr/main.yml
      tags: version
      name: version
    - debug:
        msg: "{{ ver }}"
